# Generated by Django 6.0.6 on 2026-08-15 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amendes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_id', models.IntegerField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('montant_a_payer', models.FloatField(blank=True, null=True)),
                ('montant_paye', models.FloatField(blank=True, null=True)),
                ('date_enregistrement', models.TextField(blank=True, null=True)),
                ('enregistre_par', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amendes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecaissementSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_id', models.IntegerField(blank=True, null=True)),
                ('objet', models.TextField(blank=True, null=True)),
                ('date_decaissement', models.TextField(blank=True, null=True)),
                ('montant_decaisse', models.FloatField(blank=True, null=True)),
                ('montant_rembourse', models.FloatField(blank=True, null=True)),
                ('enregistre_par', models.TextField(blank=True, null=True)),
                ('heure_enregistrement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'decaissement_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemandesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre_id', models.IntegerField(blank=True, null=True)),
                ('montant_demande', models.FloatField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('date_demande', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demandes_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.TextField(blank=True, null=True)),
                ('president_id', models.IntegerField(blank=True, null=True)),
                ('secretaire_id', models.IntegerField(blank=True, null=True)),
                ('montant_hebdo', models.FloatField(blank=True, null=True)),
                ('date_reunion_derniere', models.TextField(blank=True, null=True)),
                ('date_reunion_prochaine', models.TextField(blank=True, null=True)),
                ('taux_amende', models.FloatField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('cotisation_hebdo_fixee', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'groupes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_id', models.IntegerField(blank=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('montant_epargne', models.FloatField(blank=True, null=True)),
                ('montant_social', models.FloatField(blank=True, null=True)),
                ('date_reunion', models.TextField(blank=True, null=True)),
                ('heure_enregistrement', models.TextField(blank=True, null=True)),
                ('enregistre_par', models.TextField(blank=True, null=True)),
                ('caisse_sociale', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('epargne', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'historique_epargne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_id', models.IntegerField(blank=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('date_reunion', models.TextField(blank=True, null=True)),
                ('heure_enregistrement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historique_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalPrets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_id', models.IntegerField(blank=True, null=True)),
                ('objet', models.TextField(blank=True, null=True)),
                ('date_decaissement', models.TextField(blank=True, null=True)),
                ('date_echeance', models.TextField(blank=True, null=True)),
                ('montant_decaisse', models.FloatField(blank=True, null=True)),
                ('interet', models.FloatField(blank=True, null=True)),
                ('total_a_payer', models.FloatField(blank=True, null=True)),
                ('montant_paye', models.FloatField(blank=True, null=True)),
                ('solde', models.FloatField(blank=True, null=True)),
                ('date_paiement', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('enregistre_par', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal_prets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenom', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sexe', models.TextField(blank=True, null=True)),
                ('telephone', models.TextField(blank=True, null=True, unique=True)),
                ('cni', models.TextField(blank=True, null=True)),
                ('colline', models.TextField(blank=True, null=True)),
                ('quartier', models.TextField(blank=True, null=True)),
                ('avenue', models.TextField(blank=True, null=True)),
                ('maison', models.TextField(blank=True, null=True)),
                ('pin', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('groupe_id', models.IntegerField(blank=True, null=True)),
                ('doit_changer_pin', models.IntegerField(blank=True, null=True)),
                ('solde_epargne', models.FloatField(blank=True, null=True)),
                ('solde_pret', models.FloatField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('caisse_sociale', models.FloatField(blank=True, null=True)),
                ('last_login', models.TextField(blank=True, null=True)),
                ('status_presence', models.TextField(blank=True, null=True)),
                ('credit_en_cours', models.FloatField(blank=True, null=True)),
                ('credit_rembourse', models.FloatField(blank=True, null=True)),
                ('credit_restant', models.FloatField(blank=True, null=True)),
                ('solde_pret_social', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'membres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre_id', models.IntegerField(blank=True, null=True)),
                ('groupe_id', models.IntegerField(blank=True, null=True)),
                ('date_reunion', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre_id', models.IntegerField(blank=True, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('reste_a_payer', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('date_demande', models.TextField(blank=True, null=True)),
                ('autorise_par', models.TextField(blank=True, null=True)),
                ('date_validation', models.TextField(blank=True, null=True)),
                ('groupe_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_operation', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('PENALITE', 'Pénalité de retard'), ('Octroi de Crédit', 'Octroi de Crédit'), ('Remboursement Crédit', 'Remboursement Crédit')], default='DEPOT', max_length=50)),
                ('statut', models.CharField(default='ACTIF', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.membres')),
            ],
            options={
                'ordering': ['-date_transaction'],
            },
        ),
    ]
