# Generated by Django 6.0.6 on 2026-08-15 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant demandé en BIF', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('taux_interet', models.DecimalField(decimal_places=2, help_text="Taux d'intérêt annuel en %", max_digits=5)),
                ('duree_mois', models.PositiveIntegerField(help_text='Durée de remboursement en mois')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('SOLDE', 'Soldé')], default='EN_ATTENTE', max_length=15)),
                ('motif', models.TextField(blank=True, help_text='Description du projet ou motif de la demande', null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_approbation', models.DateTimeField(blank=True, help_text='Date à laquelle le prêt a été approuvé ou rejeté', null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='core.membres')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.DeleteModel(
            name='Prets',
        ),
    ]
