# Generated by Django 6.0.6 on 2026-08-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pret_delete_prets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('SOLDE', 'Soldé'), ('EN_ATTENTE_AGENT', 'En attente de vérification (Agent)'), ('EN_ATTENTE_DIRECTEUR', 'En attente d approbation (Directeur)'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='pret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=2, help_text="Taux d'intérêt trimestriel en %", max_digits=5),
        ),
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.IntegerField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté')], default='En attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membres')),
            ],
        ),
    ]
