# Generated by Django 6.0.6 on 2026-08-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pret_date_approbation_alter_pret_motif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='motif',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la demande'),
        ),
    ]
