# Generated by Django 6.0.6 on 2026-08-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_demandepret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membres',
            options={'managed': False, 'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
    ]
