# Generated by Django 6.0.6 on 2026-08-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_membres_options'),
    ]

    operations = [
    ]
