# Generated by Django 6.0.6 on 2026-08-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20260818_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupes',
            options={'managed': False, 'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
    ]
