# Generated by Django 6.0.6 on 2026-08-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_groupes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du partenaire')),
                ('code_partenaire', models.CharField(max_length=20, unique=True, verbose_name='Code unique')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse physique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
            ],
        ),
        migrations.AlterField(
            model_name='pret',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('SOLDE', 'Soldé'), ('EN_ATTENTE_AGENT', 'En attente de vérification (Agent)'), ('EN_ATTENTE_DIRECTEUR', 'En attente d approbation (Directeur)')], default='EN_ATTENTE', max_length=50),
        ),
    ]
