# Generated by Django 6.0.6 on 2026-09-03 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborateurPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur Partenaire'), ('OPERATEUR', 'Opérateur de Saisie')], default='OPERATEUR', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborateurs', to='core.partenaire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
