# Generated by Django 6.0.6 on 2026-10-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ticketsupport_messageticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='type_operation',
            field=models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('AMENDE', 'Amende'), ('CAISSE_SOCIALE', 'Caisse Sociale'), ('PENALITE', 'Pénalité de retard'), ('Octroi de Crédit', 'Octroi de Crédit'), ('Remboursement Crédit', 'Remboursement Crédit')], default='DEPOT', max_length=50),
        ),
    ]
