# Generated by Django 6.0.6 on 2026-10-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_transactionhistory_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='est_archive',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé (Accordé)'), ('ATTRIBUE', 'Attribué (Viré / Versé)'), ('REJETE', 'Rejeté'), ('SOLDE', 'Soldé'), ('EN_ATTENTE_AGENT', 'En attente de vérification (Agent)'), ('EN_ATTENTE_DIRECTEUR', 'En attente d approbation (Directeur)')], default='EN_ATTENTE', max_length=50),
        ),
    ]
