# Generated by Django 6.0.6 on 2026-10-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pret_est_archive_alter_pret_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
