# Generated by Django 6.0.6 on 2026-10-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transactionhistory_date_validation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteMarchand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('LUMICASH', 'LumiCash'), ('ECOCASH', 'EcoCash'), ('E_INOTI', 'e-Inoti (Bancobu)')], max_length=50, unique=True, verbose_name='Opérateur')),
                ('numero_compte', models.CharField(max_length=100, verbose_name='Numéro de compte / Code Marchand')),
                ('libelle_compte', models.CharField(max_length=150, verbose_name='Nom du titulaire / Compte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
        ),
    ]
