from django.urls import path
from . import views
from core import views
from django.views.generic import TemplateView

app_name = 'core'

urlpatterns = [
    path('', views.login_view, name='home'),
    path('', views.home_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('partner/login/', views.partner_login_view, name='partner_login'),
    path('partner/', views.partner_dashboard_view, name='partner_dashboard'),
    path('partner/dashboard/', views.partner_dashboard_view, name='partner_dashboard'),
    path('partner/members/', views.partner_members_view, name='partner_members'),
    path('partner/reports/', views.partner_reports_view, name='partner_reports'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('manager/', views.manager_dashboard_view, name='manager_dashboard'),
    path('manager/credit/<int:membre_id>/', views.grant_credit_view, name='grant_credit'),
    path('manager/loans/<int:pret_id>/<str:action>/', views.update_loan_status_view, name='update_loan_status'),
    path('manager/export/excel/', views.export_caisse_sociale_excel, name='export_caisse_sociale_excel'),
    path('manager/export/pdf/', views.export_caisse_sociale_pdf, name='export_caisse_sociale_pdf'),
    path('manager/nouveau-membre/', views.add_member_view, name='add_member'),
    path('manager/partenaire/ajouter/', views.ajouter_partenaire_view, name='ajouter_partenaire'),
    path('manager/caisse-sociale/enregistrer/', views.enregistrer_caisse_sociale_view, name='enregistrer_caisse_sociale'),
    path('manager/presences/enregistrer/', views.enregistrer_presences_view, name='enregistrer_presences'),
    path('manager/transaction/<int:membre_id>/', views.add_transaction_view, name='add_member_transaction'),
    path('membre/<int:membre_id>/', views.member_detail_view, name='member_detail'),
    path('membres/rechercher/', views.search_member_view, name='search_member'),
    path('membre/<int:membre_id>/appliquer-penalite/', views.apply_penalty_view, name='apply_penalty'),
    path('membres/<int:membre_id>/changer-groupe/', views.changer_groupe_membre_view, name='changer_groupe_membre'),
    path('membres/<int:membre_id>/retirer-groupe/', views.retirer_groupe_view, name='retirer_groupe'),
    path('membres/<int:membre_id>/changer_groupe/', views.changer_groupe_view, name='changer_groupe'),
    path('transaction/ajouter/<int:membre_id>/', views.add_transaction_view, name='add_transaction'),
    path('transactions/filtrer/', views.filtered_transactions_view, name='filtered_transactions'),
    path('transaction/<int:transaction_id>/', views.transaction_detail_view, name='transaction_detail'),
    path('transaction/<int:transaction_id>/pdf/', views.export_transaction_pdf, name='export_transaction_pdf'),
    path('transaction/<int:transaction_id>/edit/', views.edit_transaction_view, name='edit_transaction'),
    path('transaction/<int:transaction_id>/delete/', views.delete_transaction_view, name='delete_transaction'),
    path('transaction/ajouter/<int:pk>/', views.add_transaction_view, name='add_transaction'),
    path('rapport/financier/', views.financial_report_view, name='financial_report'),
    path('demande-pret/', views.request_loan_view, name='request_loan'),
    path('historique-prets/', views.list_loans_view, name='loan_history'),
    path('pret/<int:pret_id>/', views.loan_detail_view, name='loan_detail'),
    path('calculateur-credit/', views.loan_calculator_view, name='loan_calculator'),
    path('credits-en-attente/', views.list_pending_loans_view, name='pending_loans'),
    path('credit/ajouter/<int:membre_id>/', views.grant_credit_view, name='add_credit'),
    path('contrat-credit/<int:transaction_id>/pdf/', views.generate_loan_contract_pdf, name='generate_loan_contract'),
    path('agent/valider-pret/<int:pret_id>/', views.valider_par_agent, name='valider_par_agent'),
    path('manager/approbation-pret/<int:pret_id>/', views.approbation_finale_directeur, name='approbation_finale_directeur'),
    path('employe/creer/', views.create_employee_view, name='create_employee'),
    path('export/members/pdf/', views.export_members_pdf, name='export_members_pdf'),
    path('export/members/csv/', views.export_members_csv, name='export_members_csv'),
    path('export/loans/csv/', views.export_loans_csv, name='export_loans_csv'),
    path('export/loans/excel/', export_loans_excel := views.export_loans_excel, name='export_loans_excel'),
    path('export/loans/pdf/', views.export_loans_pdf, name='export_loans_pdf'),
    path('export/members/excel/', views.export_members_excel, name='export_members_excel'),
    path('export/transactions/pdf/', views.export_transactions_pdf, name='export_transactions_pdf'),
    path('profil/', views.member_profile_view, name='member_profile'),
    path('agent/valider-pret/<int:pret_id>/', views.valider_par_agent, name='valider_par_agent'),
    path('services/qr-code/', views.member_qr_view, name='member_qr'),
    path('services/predictions-ia/', views.ai_predictions_view, name='ai_predictions'),
    path('services/security-pin/', views.security_pin_view, name='security_pin'),
    path('admin/reset-pin/', views.admin_reset_pin, name='admin_reset_pin'),
    path('admin/toggle-status/', views.admin_toggle_status, name='admin_toggle_status'),
    path('admin/planifier-reunion/', views.admin_planifier_reunion_view, name='admin_planifier_reunion'),
    path('groupes/creer/', views.creer_groupe_view, name='creer_groupe'),
    path('groupes/<int:groupe_id>/archiver/', views.archiver_groupe_view, name='archiver_groupe'),
    path('groupes/<int:groupe_id>/restaurer/', views.restaurer_groupe_view, name='restaurer_groupe'),
    path('groupes/<int:groupe_id>/assigner-partenaire/', views.assigner_partenaire_groupe_view, name='assigner_partenaire_groupe'),
    path('saisie-hebdomadaire/', views.saisie_hebdomadaire_view, name='saisie_hebdomadaire'),
    path('about/', views.about_view, name='about'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('contact/', views.contact_view, name='contact'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('terms/', views.terms_view, name='terms'),
    path('accessibility/', views.accessibility_view, name='accessibility'),
]